### ISSUE TITLE
Hide cursor in fullscreen mode

### ISSUE THREAD

**Issue by samo790** [smarkusg/dgen#1]
Actually the mouse cursor is always showed, perhaps it could be hide when in fullscreen mode

**Comment by smarkusg** [comment]
Does the problem also occur on SDL1 ?
From what I noticed it occurs on SDL2(sdl12-compat).
Can you confirm this ?
This was intentionally done. The cursor on SDL-2.2.28 was behaving a bit strangely when hiding it.
Especially in window mode. It could be hidden and to bring it back required a lot of moving and clicking of the mouse.
Once the mouse was in a different position, other programs could be started.
As far as I know, version 2.2.30 already has this fixed, but I have not yet checked whether mouse hiding works.

**Comment by smarkusg** [comment]
Fixed for SDL2 - mouse hide
Binary at: https://github.com/smarkusg/dgen/releases/tag/snapshot-7032024

**Comment by samo790** [comment]
@Javier & Marek

Ok, tested some more with new exe/GUI

- Mouse cursor in SDL2 now sort of works, it hide the mouse correctly
- In GUI: 320x256 checkbox did not saved at exit, maybe another tooltype to
add?
- In main config settings, actually scale2x was choosen by default, i tried
to see if instead normal "scale" was faster but unfortunately seems pretty
the same in term of general performance, so scale2x is maybe the right
choice as default for now (and it looks better aswell)

Closed #1 <https://github.com/smarkusg/dgen/issues/1> as completed.
